MS(display_get_bitdepth)
MS(display_get_height)
MS(display_get_width)
MS(__profile_counters)
MS(__rdpq_fill_rectangle_offline)
MS(__rdpq_fixup_mode3)
MS(__rdpq_set_fill_color)
MS(__rdpq_set_mode_fill)
MS(__rdpq_tex_blit)
MS(__rdpq_write8_syncchangeuse)
MS(mixer_ch_get_pos)
MS(mixer_ch_play)
MS(mixer_ch_playing)
MS(mixer_try_play)
MS(profile_register)
MS(rdpq_attach)
MS(rdpq_detach_show)
MS(rdpq_set_mode_yuv) // put in DSO?
MS(rdpq_set_texture_image)
MS(rsp_yuv_data_end) // put in DSO?
MS(rspq_block_begin_reuse)
MS(rspq_block_end)
MS(rspq_block_free)
MS(rspq_block_run)
MS(rspq_overlay_register)
MS(rspq_overlay_share_state)
MS(rspq_overlay_unregister)
MS(stat)
MSP(strncpy, char* strncpy())
MS(__peek_varint_u64)
MS(__rdpq_font_load_builtin_2)
MS(asset_load)
MS(rdpq_call_deferred)
MS(rdpq_font_free)
MS(rdpq_font_load)
MS(rdpq_paragraph_build)
MS(rdpq_paragraph_free)
MS(rdpq_paragraph_render)
MS(rdpq_text_register_font)
MS(rdpq_text_unregister_font)
MS(vi_get_aspect_ratio)
MSP(expf, float expf(float))
MS(wav64_close)
MS(wav64_load)
MS(wav64_seek)
